config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/auth/twitter', as: :login

  get '/auth/twitter/callback', to: 'sessions#create'

  resources :tweets, only: [:create, :new, :update]

  resources :dashboard, only: [:index]

  get '/logout', as: :logout, to: 'sessions#destroy'
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth_info)
    user = find_or_create_by(uid: auth_info.uid)
    #so we can make sure changes are reflected. update_attributes and find_or_create_by are built in methods
    user.update_attributes(
      name:               auth_info.extra.raw_info.name,
      screen_name:        auth_info.extra.raw_info.screen_name,
      profile_picture:    auth_info.extra.raw_info.profile_image_url,
      oauth_token:        auth_info.credentials.token,
      oauth_token_secret: auth_info.credentials.secret
    )

    user
  end

  def twitter_client
    @client ||= Twitter::REST::Client.new do |config|
      config.consumer_key = ENV['twitter_key']
      config.consumer_secret = ENV['twitter_secret']
      config.access_token = oauth_token
      config.access_token_secret = oauth_token_secret
    end
  end

  def twitter_timeline
    twitter_client.home_timeline
  end

  def follower_count
    twitter_client.user.followers_count
  end

  def following_count
    twitter_client.user.friends_count
  end

  def background_picture
    twitter_client.user.profile_background_image_url_https
  end

  def location
    twitter_client.user.location
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
      redirect_to dashboard_index_path
    else
      redirect_to root_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  private

  def oauth
    request.env['omniauth.auth']
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def new
  end

  def create
    current_user.twitter_client.update(params[:tweet])
    redirect_to dashboard_index_path
  end

  def update
    current_user.twitter_client.favorite(params[:id])
    redirect_to dashboard_index_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Twitter::Autolink
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/index.html.erb
<!DOCTYPE html>
<% if current_user %>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">

  <title>Narrow Jumbotron Template for Bootstrap</title>

  <!-- Bootstrap core CSS -->
  <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="jumbotron-narrow.css" rel="dashboard">

  <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
  <!--[if lt IE 9]>
  <script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
  <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>
<div class="container">
  <div class="header clearfix">
    <nav>
      <ul class="nav nav-pills pull-right">
        <li role="presentation" class="active"><%= link_to "Logout", logout_path %></li>
        <!--<li role="presentation"><a href="#">About</a></li>-->
        <!--<li role="presentation"><a href="#">Contact</a></li>-->
      </ul>
    </nav>
    <h3 class="text-muted">TwitterFeed</h3>
  </div>

  <div class="jumbotron">
    <h2>Hello, <%= current_user.name %></h2>
    <%= image_tag src=current_user[:profile_picture], size: "110x110", class: "img-circle img-thumbnail", alt: "Awesome Pic!" %>
    <h4><%= current_user.screen_name %></h4>
    <h4>Followers: <%= current_user.follower_count %></h4>
    <h4>Following: <%= current_user.following_count %></h4>
    <h3>Location: <%= current_user.location %></h3>

    <p><a class="btn btn-lg btn-success" <%= link_to "Tweet", new_tweet_path %></a></p>
  </div>

  <div class="row marketing">
    <div class="col-lg-6">
      <h4>Feed The Day!</h4>

      <p>Studies show that tweeting once per minute can prevent boredom and increase your blood cell count.</p>

      <h4>Tweeting Is Giving</h4>

      <p>Telling someone something only lasts until they forget it. Tweeting someone something lasts forever.</p>
    </div>

    <div class="col-lg-6">
      <h4>Feeding...Forever</h4>

      <p>
      <ol>
        <% current_user.twitter_timeline.each do |tweet| %>
          <li><%= link_to "favorite", tweet_path(id: "#{tweet.id}"),method: :put, class: "btn btn-tny btn-danger" %><%= tweet.text %></li>
        <% end %>
      </ol>
      </p>
    </div>
  </div>
</div>
<!-- /container -->

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>
<% else %>
  redirect_to: root_path
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterEngine</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/new.html.erb
<!DOCTYPE html>
<% if current_user %>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="jumbotron-narrow.css" rel="dashboard">

  <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
  <!--[if lt IE 9]>
  <script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
  <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>
<div class="container">
  <div class="header clearfix">
    <h3 class="text-muted">Feed the need, to TWEET!</h3>
  </div>

  <div class="jumbotron">
    <h2>Brand New Tweet</h2>
    <%= form_tag(tweets_path) do %>
      <%= label_tag :tweet %>
      <%= text_field_tag :tweet %>
      <%= submit_tag "tweet it", class: "btn btn-sm btn-success" %>
    <% end %>
  </div>
</div>
</body>
</html>
<% else %>
  redirect_to: root_path
<% end %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">

  <!-- Bootstrap core CSS -->
  <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="jumbotron.css" rel="stylesheet">

  <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
  <!--[if lt IE 9]>
  <script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
  <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
<h4>TwitterFeed</h4>
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <h1>What's feeding you today?</h1>

    <p>Life is too short to sit back and enjoy it. Get tweeting, and feeding, and reading about other people's feeding!</p>

    <p><%= link_to "Login with Twitter", login_path, class: "btn btn-primary btn-lg" %></p>
  </div>
</div>
  <footer>
    <p>&copy; Creative License 2015</p>
  </footer>
</div>
<!-- /container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>